### ISSUE TITLE
[FEEDBACK] Issue using with `@monaco-editor/react` in NextJS

### ISSUE THREAD

**Issue by burtek** [lukasbach/monaco-editor-auto-typings#9]
Not sure if bug or feature request... 🤔 

Right now I'm unable to use `monaco-editor-auto-typings` with `@monaco-editor/react` because it makes some global CSS get imported from `node_modules` which is what NextJS [doesn't like](https://nextjs.org/docs/messages/css-npm).

More precisely, `monaco-editor-auto-typings` imports `monaco-editor` in [`AutoTypings.ts`](https://github.com/lukasbach/monaco-editor-auto-typings/blob/master/packages/core/src/AutoTypings.ts#L7=) which in turn indirectly imports global css in `monaco-editor\esm\vs\base\browser\ui\actionbar\actionViewItems.js`.

The solution would be to not import `monaco-editor` but that would break the fallback. Another solution would be to have another export (i.e. `monaco-editor-auto-typings/nextjs`) that doesn't auto-import `monaco-editor` but requires `monaco` instance to be passed in options.

Is there any chance to get `monaco-editor-auto-typings` working with NextJS ?

**Comment by lukasbach** [comment]
Can you try again in v0.3.1 when [passing in your own `monaco` instance in the options](https://lukasbach.github.io/monaco-editor-auto-typings/docs/interfaces/Options.html#monaco)? I just updated the import in v0.3.1 to only dynamically import monaco if it is not passed through, so hopefully this should fix it.

**Comment by burtek** [comment]
Tried 0.3.2, for some reason it still doesn't work. I've been trying to find the cause for this for a few hours now...

**Comment by burtek** [comment]
Okey, got it.

Dynamic imports won't work, as [those are still compiled](https://github.com/vercel/next.js/issues/30942#issuecomment-960614284) (just might not get used in runtime) and the global css check happens at compile time.

**Comment by burtek** [comment]
Got it working with the hack of using [next-remove-imports](https://www.npmjs.com/package/next-remove-imports) for now, would prefer an out-of-box solution rather than hacks, though :/

**Comment by lukasbach** [comment]
Huh, interesting, would not have thought that. I'll look into alternatives for that in the coming week. Out of curiosity, how do you import monaco on your side to be passed through to this package such that the css files are not imported?

**Comment by burtek** [comment]
I use `@monaco-editor/react` rather than `monaco-editor`, as it is added advantage of being NextJs compatible. `monaco` instance comes then from it's `onMount` prop

**Comment by softmarshmallow** [comment]
Having same issue here.
First of all, you may want to add `monaco-editor` as a `peerDependencies` not `dependencies` in this package.json

**Comment by softmarshmallow** [comment]
Also pinging this new issue, will open a new issue once confirmed.

After hacking with @burtek 's solution, i got it to compile & run, but then i get this message. (using same next12 configuration)

```
Unhandled Runtime Error
TypeError: path.dirname is not a function

Call Stack
AutoTypings.eval
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (213:111)
step
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (67:22)
Object.eval [as next]
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (48:52)
eval
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (42:70)
new Promise
<anonymous>
__awaiter
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (38:11)
AutoTypings.resolveContents
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (196:15)
new AutoTypings
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (102:13)
Function.eval
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (129:46)
step
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (67:22)
Object.eval [as next]
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (48:52)
fulfilled
../node_modules/monaco-editor-auto-typings/lib/AutoTypings.js (39:57)
```

**Comment by softmarshmallow** [comment]
Here is my repo. but i dropped the changes yesterday and decided to wait until this issue is solved.
Will try to add a reproducible code on sub branch later
https://github.com/gridaco/designto-code


Thanks anyway!

**Comment by softmarshmallow** [comment]
Hi. here's the commit that captures the issue
https://github.com/gridaco/designto-code/tree/snapshot-of-bug-monaco-autotype-next12

You may see the latest commit

**Comment by softmarshmallow** [comment]
This seems to be a `@monaco-editor/react`' issue.

I had a same issue when exported a logic to a different file (addCommand) and the same issue occurred.
(Don't know why.)

**Comment by lukasbach** [comment]
I now moved monaco-editor to the peerDependencies, and added a new entrypoint. You can try to import from `"monaco-editor-auto-typings/customeditor"` instead of `"monaco-editor-auto-typings"`. It should export the same symbols, but have no imports of `monaco-editor` at all except for type imports. This fix is available in version v0.4.0.

**Comment by burtek** [comment]
Works great now! Thanks you very much! :)

**Comment by ClintH** [comment]
I'm also having the error 'path.dirname is not a function' error, even though importing from 'monaco-editor-auto-typings/custom-editor' and passing in a monaco instance. 

I am using Lit, TS & Vite.

Uncaught (in promise) TypeError: path.dirname is not a function
    at AutoTypingsCore2.<anonymous> (chunk-D6HROQ3V.js?v=c1a822df:1459:94)
    at step (chunk-D6HROQ3V.js?v=c1a822df:1308:23)
    at Object.next (chunk-D6HROQ3V.js?v=c1a822df:1255:18)
    at chunk-D6HROQ3V.js?v=c1a822df:1241:71
    at new Promise (<anonymous>)
    at __awaiter (chunk-D6HROQ3V.js?v=c1a822df:1223:14)
    at AutoTypingsCore2.resolveContents (chunk-D6HROQ3V.js?v=c1a822df:1442:16)
    at new AutoTypingsCore2 (chunk-D6HROQ3V.js?v=c1a822df:1353:14)
    at Function.<anonymous> (chunk-D6HROQ3V.js?v=c1a822df:1370:24)
    at step (chunk-D6HROQ3V.js?v=c1a822df:1308:23)

[Here's a minimal repro](https://stackblitz.com/edit/vitejs-vite-ului2l?file=src/code-editor.ts)

I am not savvy when it comes to build processes, so maybe there is a Vite/Rollup setting I'm missing. 

Any tips appreciated! :)

**Comment by FreePhoenix888** [comment]
For those who do now want to read all the comments of this issue.
# Solution
Import from `monaco-editor-auto-typings/custom-editor` instead of `monaco-editor-auto-typings`

## Before
```ts
import { AutoTypings, LocalStorageCache } from "monaco-editor-auto-typings";
```
## After 
```ts
import { AutoTypings, LocalStorageCache } from "monaco-editor-auto-typings/custom-editor";
```
